config/routes.rb
Pt::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
	
	resources :files
	
	resources :projects do
		resources :tickets
	end	
		
	resources :tickets do
		resources :comments
	end
	
  namespace :admin do
  	root :to => "base#index"
  	resources :states do
  		member do
  			get :make_default
  		end
  	end
  	
  	resources :users do
  		resources :permissions
  	end
  	
  end
	
	put '/admin/users/:user_id/permissions',
										:to => 'admin/permissions#update',
										:as => :update_user_permissions
	root :to => "projects#index"
		

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tickets, :dependent => :destroy
	has_many :permissions, :as => :thing
	
	validates :name , :presence => true , :uniqueness => true
	validates :body , :presence => true
	
	scope :readable_by , lambda { |user| 
											 joins(:permissions).where(:permissions => { :action => "view",
											 																						 :user_id => user.id})
	}
	
	def self.for(user)
		user.admin? ? Project : Project.readable_by(user)
	end
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authorize_admin!, :except => [:index, :show]
	before_filter :authenticate_user!, :only => [:index, :show]
	before_filter :find_project, :except => [:index, :new, :create]
	
	def index
		@projects = Project.for(current_user).all
		@title = "Listing all Projects"
	end
	
	def new
		@project = Project.new
		@title = "New Project"
	end
	
	def edit
	end
	
	def show
	end
	
	def create
		@project = Project.new(params[:project])
		if @project.save
			flash[:notice] = "Project successfully created"
			redirect_to @project
		else
			flash[:alert] = "Project was not created"
			render 'new'
		end
	end
	
	def update
		if @project.update_attributes(params[:project])
			flash[:notice] = "Project successfully updated"
			redirect_to @project
		else
			flash[:alert] = "Project was not updated"
			render 'edit'
		end
	end
	
	def destroy
		@project.destroy
		flash[:notice] = "Project has been deleted"
		redirect_to root_url
	end
	
	private

	def find_project
      @project = Project.for(current_user).find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking" +
                      " for could not be found."
      redirect_to projects_path
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= semantic_form_for(@project) do |f| %>
	<%= f.inputs do %>
		<%= f.input :name , :label => "Project Name" %>
		<%= f.input :body, :label => "Project Description" %>
	<% end %>
	
	<%= f.buttons %>

<% end %>

app/views/projects/edit.html.erb
<h2>Edit <%= @project.name %></h2><br />

<%= render 'form' %>

<%= link_to 'Back', projects_url %>

app/views/projects/index.html.erb
<%= admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>

<h2>Projects</h2> 

<ul id='projects'>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>Create Project</h1><br />

<%= render 'form' %>

app/views/projects/show.html.erb
<script type="text/javascript">
	$(function(){
		$(".tickets").css("list-style","none");
		$(".tickets").css("background-color","#ccc");
		$(".tickets").css("margin-bottom","10px");
		$(".tickets").css("padding","10px");
	})
</script>

<h2><%= @project.name %></h2>
<ul class="projects">
	<li>
		<%= @project.name %><br />
		<%= @project.body %><br />
	<%= admins_only do%>	
		<%= link_to 'Edit', edit_project_path(@project) %><br />
		<%= link_to 'Destroy', @project, confirm: 'Are you sure?', method: :delete %><br />
	<% end %>	
		<%= link_to 'Back', projects_url %> <br />
	</li>
	
		
	<h2>Project Tickets</h2>
	
	<% @project.tickets.each do |ticket| %>
	<ul class="tickets">
		<li>
			<b><%= link_to ticket.name, [@project, ticket] %></b><br />
			<li>
				<%= render ticket.state if ticket.state %><br />
				#<%= ticket.id %> - <%= link_to ticket.name, [@project, ticket]%>
			</li>
			<%= ticket.body %><br />
		</li>
	</ul>
	<% end%>
	
	<%= authorized?("create tickets".to_sym, @project)  do %>	
		<%= link_to 'New Ticket', new_project_ticket_path(@project) %>	
	<% end %>
	
</ul>